owncloud/brute_force_protection

- README.md
- appinfo/info.xml
While researching the app so that I can document it, https://github.com/owncloud/documentation/issues/4334, I started going through the description. However, while pretty clear, I felt that the wording could be further refined and tightened, so that it's sharper and easier to understand. 
:information_desk_person: No negative reflection is intended toward the original authors, by me saying this.
> Refine the app's description

- lib/BruteForceProtectionConfig.php
- lib/Db/FailedLoginAttemptMapper.php
- lib/Jobs/ExpireOldAttempts.php
- lib/Throttle.php
- tests/BruteForceProtectionConfigTest.php
- tests/Db/FailedLoginAttemptMapperTest.php
- tests/Jobs/ExpireOldAttemptsTest.php
- tests/ThrottleTest.php
fix for #33 
- default time threshold value changed from 600 to 60
Ban algorithm change as:
- find last failed login attempts of uid and ip combination, let the time of the attempt X
- Count failed login attempts between the interval [ (X-time threshold) , X ]
- If the count of the attempts more than tolerance, ban until X + ban period.
@individual-it , in short, it should work as you expect in the beginning.
> fix ban logic

- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
When setting/restoring brute-force-protection settings, handle passing empty values to ``runOcc``
Fixes "dumb" test fails, particularly when the code is restoring previous values that were empty.
> Handle blank values when setting in acceptance tests

- tests/acceptance/features/lib/BlockedUserPage.php
Old forms of the constant names were deprecated by https://github.com/owncloud/core/pull/32781/commits/db4608ace28ed62a00173021416951fb7ac3d994
Use the new forms that have underscores.
> adjust acceptance test time constant names

- Makefile
fix for `make appstore` command, we have no css folder in this app.
> clean up makefile make appstore command

- Makefile
Related to issue https://github.com/owncloud/QA/issues/609
Cleanup leftover rubbish related to ``COMPOSER_BIN`` and a local ``composer.phar``
These days we are everywhere expecting that `composer` is already installed on a developer or CI system.
> Cleanup Makefile unneeded composer references

- .drone.yml
- appinfo/info.xml
- composer.json
- composer.lock
- vendor-bin/behat/composer.json
core stable10 no longer supports PHP 5.6
https://github.com/owncloud/core/pull/34698
> Drop PHP 5.6

- .drone.yml
Add drone matrices to run test against latest stable release tarball.
Related Issue https://github.com/owncloud/QA/issues/611
> Run acceptance tests against latest stable release of core

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
core PR https://github.com/owncloud/core/pull/36032 implemented checking of the HTTP status of various `Given` steps. We expect that `Given` steps always "do a good thing" in setting up the environment of the scenario. When they access an API the HTTP status should be `2xx`.
In `brute_force_protection` it is unusual. We are "setting up"  the system to be in a blocking state. We purposely send some invalid API requests, which have only the side-effect that the server is pushed into the blocking state.
IMO it seems reasonable that those purposely invalid API requests be `When` steps. So I made them `When` steps, which do not have their HTTP status checked.
> Adjust given-when steps for API blocking tests

- tests/acceptance/features/bootstrap/bootstrap.php
The core `Page` objects from core `tests/acceptance/features/lib` are already loaded by the core `tests/acceptance/features/bootstrap/bootstrap.php` - it does not need to be done again here.
(I noticed this when converting drone in the `configreport` app which also had other differences in its `tests/acceptance/features/bootstrap/bootstrap.php` )
> Remove unneeded acceptance test bootstrap.php code

- .drone.starlark
- .drone.yml
- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/setup_trusted_proxies.sh
Fixes issue #88 
The `ip` command is not available any more in the `owncloudci/php` docker. But `hostname`  is available. Actually that is useful - `hostname -I` outputs the IP addresses of all interfaces. We can loop around and set a `trusted_proxies` entry for each of those. (Usually there is just one when being run in the drone-docker environment.
If `setup_trusted_proxies.sh` script is useful as a "test setup helper" in core and/or other repos, then we can move it into core `tests/acceptance`. For no, we want to get CI green here!
> Set trusted_proxies in acceptance tests

- .drone.starlark
- vendor-bin/behat/composer.json
It is needed by core `HttpRequestHelper.php` `parseResponseAsXml`
And there is no longer any need to `make install-composer-deps` in the testrunner core folder, because those dependencies are not used by behat any more.
> Add sabre/xml to behat dependencies

- .drone.starlark
- .drone.yml
This PR adds `X-FORWADED-HEADER` to be used in the apache server. The `X-Forwarded-For (XFF)`header is a de-facto standard header for identifying the originating IP address of a client connecting to a web server through an HTTP proxy or a load balancer.
https://github.com/owncloud/brute_force_protection/issues/98
Draft PR: https://github.com/owncloud/brute_force_protection/pull/103 asserts that the modifications made in this PR fixes issue https://github.com/owncloud/brute_force_protection/issues/98
> Use X-FORWADED-FOR header in Apache server

- Makefile
I was doing `make clean` in this app and realised that it was not removing the `vendor` and `vendor-bin` stuff like is the behaviour of `make clean` in the other apps.
Adjust the `clean` Makefile target to be like other apps.
> fix make clean so it cleans the dependencies

- phpstan.neon
- `bootstrapFiles` section
- remove the `excludes_analyse` section, the `appinfo/Migrations` code gets analyzed OK now
> Adjust phpstan.neon for phpstan 0.12.26 onwards

- .drone.star
- appinfo/Migrations/Version20191109111104.php
- appinfo/info.xml
- lib/BruteForceProtectionConfig.php
- lib/Db/FailedLinkAccess.php
- lib/Db/FailedLinkAccessMapper.php
- lib/Db/FailedLoginAttemptMapper.php
- lib/Exceptions/LinkAuthException.php
- lib/Hooks.php
- lib/Jobs/ExpireOldAttempts.php
- lib/Throttle.php
- templates/settings-admin.php
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/unit/Controller/SettingsControllerTest.php
- tests/unit/Db/FailedLinkAccessMapperTest.php
- tests/unit/Db/FailedLoginAttemptMapperTest.php
- tests/unit/HooksTest.php
- tests/unit/Jobs/ExpireOldAttemptsTest.php
- tests/unit/ThrottleTest.php
Fixes #57 
- Legacy OC\User hooks changed with EventDispatcher events
- Brute force protection added for public link share authentications.
- Brute force protection settings now common for login and public link share auth.
> Protect public links password page

- lib/Exceptions/LinkAuthException.php
To be able to show error message and return correct return response, `LinkAuthException` should inherit from `LoginException`
- Fixes #134
> LinkAuthException should inherit from LoginException for proper catching on core

- .drone.star
- composer.json
- composer.lock
- vendor-bin/behat/composer.json
Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP  7.4 for the dependencies to sort themselves out with composer 2.0
> Adjust PHP dependencies for composer 2.0

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
Related issue https://github.com/owncloud/brute_force_protection/issues/146
These new and changed scenarios use core test steps added in PR https://github.com/owncloud/core/pull/38204
1) adjust the existing scenario for downloading a file in a public link folder. It was previously strange - it tried to download using a step for the "last publicly shared file" and was probably attempting to fetch the actual public link folder. Now it clearly downloads a file that is in the public link foldder.
2) Add scenarios to upload a file into a public link folder, and create a folder in a public link folder. They check that brute force protection locks those things out after 3 attempts with the wrong password.
> [tests-only] Add tests for upload and create folder in a public link

- lib/Db/FailedLinkAccessMapper.php
- lib/Db/FailedLoginAttemptMapper.php
`doctrine/dbal` was updated yesterday in core https://github.com/owncloud/core/pull/38647
Some methods have been deprecated, and `phan` reports those and fails the CI.
Suppress the deprecation warnings for now.
I raised issue #155 to actually adjust the code "some time".
> Suppress PhanDeprecatedFunction for doctrine/dbal changes

- .drone.star
This is an update on drones.star file 
- using drone-cancel-previous-builds
- using thegeeklab/drone-github-comment instead of jmccann/drone-github-comment for github comments 
- moving docker image references to constants
- using caches images
- Do not run PHP unit tests with Oracle by default
- Part of issue: 
- https://github.com/owncloud/QA/issues/700
- https://github.com/owncloud/QA/issues/717
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728
- https://github.com/owncloud/core/issues/38679
> [full-ci] Updated drone starlark file

- phpunit.xml
This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198
> [tests-only][full-ci]Tidy up the phpunit xml file for brute_force_protection app

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
This PR adds the word `link` to steps to match the step implementation.
- Fixes https://github.com/owncloud/brute_force_protection/issues/176
> [full-ci] [tests-only] Refactored steps, added  missing word

- vendor-bin/phpstan/composer.json
- use the latest phpstan, which is 1.9.* series
- https://github.com/owncloud/QA/issues/777
> Bump phpstan version to 1.9

- lib/Hooks.php
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
Due to changes in OC 10.12 (not released yet), the behavior of the app has changed. This PR will bring back the old behavior.
Related to https://github.com/owncloud/brute_force_protection/issues/191
-----
OC versions 10.11 and earlier trigger a pre-login event and then a failed login event if needed. The brute login policy was applied only on the pre-login event, which happened even if the login failed afterwards.
With OC 10.12, the pre-login event happens after most of the checks have been done. This means that if the login fails, a failed login event will be triggered but not a pre-login event. This change in the order of the events causes problems with the app behavior.
In order to fix this issue, the brute login policy will also be applied when a login fails. Note that the failed …
> Apply brute login policy on failed login

- lib/Throttle.php
- tests/unit/ThrottleTest.php
Fix #200 
Please test and modify the log message if necessary.
The initial log message of a failed login is generated by: [https://github.com/owncloud/core/blob/master/lib/private/User/Manager.php#L272](https://github.com/owncloud/core/blob/master/lib/private/User/Manager.php#L272)
> Log of blocking a user
