- .gitignore
- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
- tests/acceptance/features/bootstrap/WebUIBruteForceProtectionContext.php
- tests/acceptance/features/bootstrap/bootstrap.php
- tests/acceptance/features/lib/BlockedUserPage.php
- tests/acceptance/features/lib/BruteForceProtectionPage.php
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
first step to fix #12
running the tests in drone will be next PR and then implementing API tests
> bootstrap UI tests

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
api acceptance tests infrastructure and first basic tests
need https://github.com/owncloud/core/pull/32434 and https://github.com/owncloud/core/pull/32435
> first basic API acceptance tests

- .drone.yml
run also API tests in drone
part of #12
> run API tests in drone

- .drone.yml
and remove other excess lines in ``.drone.yml``
> No su exec www data

- .drone.yml
- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
> more api tests

- appinfo/info.xml
- lib/Db/FailedLoginAttemptMapper.php
- lib/Jobs/ExpireOldAttempts.php
- tests/Db/FailedLoginAttemptMapperTest.php
- tests/Jobs/ExpireOldAttemptsTest.php
add expire old attempts scheduled job
resolves #2
> add expire old attempts scheduled job

- l10n/.tx/config
Adding configuration to allow of automated translations via transifex
> Add Automated translations via transifex

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
1) Indent 2-characters in feature files
2) Remove hard-coded password of ``user1``
> Refactor tests 20181003

- .travis.yml
- tests/ThrottleTest.php
I noticed that the LoginException case was not tested properly. It is a fix for it.
> fix time problem of apply bfp test method

- appinfo/info.xml
Because core platform is switching to Semver
> Set max-version to 10, increase patch version

- composer.lock
- tests/unit/BruteForceProtectionConfigTest.php
- tests/unit/Controller/SettingsControllerTest.php
- tests/unit/Db/FailedLoginAttemptMapperTest.php
- tests/unit/HooksTest.php
- tests/unit/Jobs/ExpireOldAttemptsTest.php
- tests/unit/ThrottleTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) Update bamarni/composer-bin-plugin (v1.3.0)  (while we are here)
> Php unit 5 to 6

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
> Adjust create user test steps

- .drone.starlark
1) support for `build()` pipeline
2) bugfix for default browser in acceptance tests
> Update to latest drone starlark code

- lib/Throttle.php
superseded of #41
@mmattel The branch was out of date, I rebased it and squashed commits. Let's see test results.
> Added userfriendly text after too many login attempts

- .drone.starlark
- .drone.yml
- composer.json
- composer.lock
- tests/unit/BruteForceProtectionConfigTest.php
- tests/unit/Controller/SettingsControllerTest.php
- tests/unit/Db/FailedLoginAttemptMapperTest.php
- tests/unit/HooksTest.php
- tests/unit/Jobs/ExpireOldAttemptsTest.php
- tests/unit/ThrottleTest.php
- vendor-bin/behat/composer.json
Similar to https://github.com/owncloud/configreport/pull/121
Note: `phpunit.xml` is already good in this app.
> Adjust tests

- .drone.starlark
- .drone.yml
- tests/unit/ThrottleTest.php
- vendor-bin/owncloud-codestyle/composer.json
like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
> Coding standard 2.0.0

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
- tests/acceptance/features/bootstrap/WebUIBruteForceProtectionContext.php
`Ip` trait was changed to `IpContext` class in core PR https://github.com/owncloud/core/pull/36771
Make the needed adjustments here.
> Adjust acceptance test for core IpContext change

- .drone.starlark
- .drone.yml
Part of issue https://github.com/owncloud/QA/issues/640
> Use new owncloudci/oracle-xe docker image in CI

- .drone.starlark
- .drone.yml
Issue https://github.com/owncloud/QA/issues/640
> Make xForwardedFor a switch in drone starlark

- .drone.star
- composer.json
- composer.lock
- lib/BruteForceProtectionConfig.php
- lib/Db/FailedLoginAttempt.php
- lib/Hooks.php
- lib/Throttle.php
- phpstan.neon
- vendor-bin/phpstan/composer.json
Related - owncloud/QA#642
1) Update phpstan to 0.12
2) Bump bamarni/composer-bin-plugin to 1.4
3) Drop PHP 7.1 from CI (including up-to-date drone starlark code)
> [Tests-Only] Update phpstan to latest version

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
like in core PR https://github.com/owncloud/core/pull/37397
It will be good to do this now, because PR #111 needs rebase and merge conflicts anyway.
> [Tests-Only] Use realistic user names in acceptance tests

- Makefile
See comment https://github.com/owncloud/brute_force_protection/issues/129#issuecomment-654813463
> Add CHANGELOG.md to release tarball

- Makefile
needed for https://github.com/owncloud/brute_force_protection/issues/31
> include img folder in make dist

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
https://github.com/owncloud/core/pull/37948 should resolve #112
We can merge this one after the core pr.
> [Tests-Only] remove @issue-112 tags from acceptance tests

- .drone.star
- lib/Db/FailedLinkAccess.php
- lib/Hooks.php
- vendor-bin/phan/composer.json
and adjust minor stuff that it reports.
> [tests-only] Enable phan version 3

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
like was done in core last week.
Fixes CI
> [tests-only] Specify skeleton in tests

- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
- tests/acceptance/features/bootstrap/WebUIBruteForceProtectionContext.php
- tests/acceptance/features/bootstrap/bootstrap.php
- tests/acceptance/features/lib/BlockedUserPage.php
- tests/acceptance/features/lib/BruteForceProtectionPage.php
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script
> [Tests-Only] enforce strict type checking in acceptace tests code

- .drone.star
- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
> [tests-only] skip blockBasedOnClientIpAddress tests in CI

- .drone.star
it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI
> [tests-only][full-ci]Use directory references from global dir variable in drone.star file

- tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
> [full-ci] [tests-only] Refactored inter scenarios space

- tests/acceptance/features/bootstrap/WebUIBruteForceProtectionContext.php
- tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
Fix login test code: get real password.
And added a test scenario to cover new behavior: can try login multiple times with invalid password
Closes https://github.com/owncloud/brute_force_protection/issues/190
Closes https://github.com/owncloud/brute_force_protection/issues/191
> [tests-only][full-ci] Fix/Add brute force protection scenarios

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
> Release 1.2.0

- .drone.star
- composer.json
- composer.lock
- bump composer dependency
- apply latest .drone.star changes from activity app
> [tests-only] [full-ci] CI changes to .drone.star and composer

- appinfo/Migrations/Version20180802194631.php
- lib/BruteForceProtectionConfig.php
- lib/Controller/SettingsController.php
- lib/Db/FailedLinkAccess.php
- lib/Db/FailedLinkAccessMapper.php
- lib/Db/FailedLoginAttempt.php
- lib/Db/FailedLoginAttemptMapper.php
- lib/Hooks.php
- lib/Panels/AdminPanel.php
- lib/Throttle.php
- tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
- tests/acceptance/features/bootstrap/WebUIBruteForceProtectionContext.php
- tests/acceptance/features/lib/BlockedUserPage.php
- tests/acceptance/features/lib/BruteForceProtectionPage.php
- tests/unit/Db/FailedLinkAccessMapperTest.php
- tests/unit/Db/FailedLoginAttemptMapperTest.php
- tests/unit/HooksTest.php
- tests/unit/ThrottleTest.php
- vendor-bin/behat/composer.json
- vendor-bin/owncloud-codestyle/composer.json
- vendor-bin/phan/composer.json
- vendor-bin/php_codesniffer/composer.json
- vendor-bin/phpstan/composer.json
Apply owncloud coding-standard v4
> [tests-only] [full-ci] owncloud coding-standard v4

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
> Release 1.3.0
